myProject_src/blog/urls.py
from django.urls import path
from . import views
from . views import PostCreateView, PostUpdateView, PostDeleteView
urlpatterns =[
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('Try/', views.Try, name='Try'),
    path('MainPage/', views.Try, name='MainPage'),
    path('detail/<int:post_id>/', views.post_detail, name='detail'),
    path('new_post/', PostCreateView.as_view(), name='new_post'),
    path('detail/<slug:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('detail/<slug:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    #path('process_upload', views.process_upload, name='process_upload'),
    path('download_combined_pdf', views.download_combined_pdf, name='download_combined_pdf'),
]

myProject_src/user/urls.py
from django.urls import path
from .import views 
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ 
    path('register/', views.register, name='register'),
   # path('login/', LoginView.as_view(template_name='user/login.html') , name='login'),
    path('login/', views.login_user, name='login'),
   # path('logout/', LogoutView.as_view(template_name='user/logout.html') , name='logout'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myProject_src/web_project/urls.py
from django.contrib import admin
from django.urls import path, include
""" from django.conf.urls.static import static
from django.conf import settings """

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
    path('', include('riskassesment.urls')),
] 

""" urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) """

myProject_src/blog/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

#tables translelated into the db
# fields are title , content ...
# db is written using pythonand needed to be transformed to sql using commands 
#1. python manage.py makemigrations from python to sql
#2. python manage.py migrate execute the sqql and create the db

def user_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return os.path.join('user', f'{instance.author.id}', filename)
    
class Post( models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    post_date = models.DateTimeField(default=timezone.now) #created first time when post is created
    post_update = models.DateTimeField(auto_now=True) #updated every time the post is alterd
    author = models.ForeignKey(User, on_delete= models.CASCADE) #user is from django tables
    uploaded_report = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    generated_pdf = models.FileField(upload_to='generated_pdfs/', blank=True, null=True)

    def __str__(self): #to return the title at the site administration
        return self.title
    
    def get_absolute_url (self):
         return reverse('detail', args=[self.pk])

    
    class Meta: #for the post to appear from new to old 
        ordering = ('-post_date',)

class Comment (models.Model): #inherits from models class
    name = models.CharField(max_length=30, verbose_name="الإسم")
    email = models.EmailField(verbose_name="البريد الإلكتروني")
    body = models.TextField(verbose_name="التعليق")
    comment_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    def __str__(self):
        return 'علق {} على {}.'.format(self.name, self.post)
    class Meta:
        ordering = ('-comment_date',)




    

myProject_src/blog/forms.py
from django import forms
from .models import Comment, Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div
class NewComment(forms.ModelForm) :
    class Meta:
        model = Comment
        fields = ('name','email','body')
        
#add one mode field to take the compliance file from user
class PostCreateForm(forms.ModelForm) :
    title = forms.CharField(label='عنوان التقرير', max_length=50)
    content = forms.CharField(label=' وصف التقرير ', widget=forms.Textarea )
    uploaded_report = forms.FileField(label='ارفاق الملف', required=True)
   
    
    class Meta:
        model = Post
        fields = ['title','content','uploaded_report']


class PostUpdateForm(forms.ModelForm):
    title = forms.CharField(label='عنوان التقرير', max_length=50)
    content = forms.CharField(label=' وصف التقرير ', widget=forms.Textarea)
    
    class Meta:
        model = Post
        fields = ['title', 'content']

myProject_src/user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserCreationForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30, help_text='اسم المستخدم يجب ان لايحتوي على مسافات')
    email = forms.EmailField(label='البريد الإلكتروني')
    first_name = forms.CharField(label='الاسم الأول', max_length=30)
    last_name = forms.CharField(label='الاسم الثاني')
    password1 = forms.CharField(label='كلمة المرور' ,  widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(label='تأكيد كلمة المرور',  widget=forms.PasswordInput(), min_length=8)
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name','password1','password2' )
        
    def clean_password(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('كلمة المرور غير متطابقة')
        return cd['password2']
    
    def cleaned_username(self):
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise forms.ValidationError('يوجد مستخدم مسجل بهذا الاسم')
        return cd['username']
    

class LoginForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30)
    password = forms.CharField(label='كلمة المرور' ,  widget=forms.PasswordInput(), min_length=8)
    class Meta:
        model = User
        fields = ('username','password' )

class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الأول', max_length=30)
    last_name = forms.CharField(label='الاسم الثاني')
    email = forms.EmailField(label='البريد الإلكتروني')

    class Meta :
        model = User
        fields = ('first_name','last_name','email')

class ProfileUpdateForm(forms.ModelForm):
   class Meta :
        model = Profile
        fields = ('image',)

myProject_src/blog/views.py
from typing import Optional
from django.shortcuts import render , get_object_or_404, redirect
from .models import Post, Comment

from django.core.files.base import ContentFile

from .forms import NewComment, PostCreateForm, PostUpdateForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django .contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from io import BytesIO

from django.http import HttpResponse
from .prepocessing import DataPreprocessor
import os
import pandas as pd
#from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
import pickle
import io
#creating views

def Try(request) :
    return render(request, 'blog/Try.html', context={'title':'Try'})

def MainPage(request) :
    return render(request, 'blog/TrMainPagey.html', context={'title':'MainPage'})

def home(request) :
    posts = Post.objects.all()
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context ={ 
    'title': 'الصفحة الرئيسية',
    'posts' : posts,
    'page' : page,
    }
    #blog/index.html refers to the file at the temblates folder 
    return render(request, 'blog/index.html', context)

def about(request) :
    return render(request, 'blog/about.html', context={'title':'من أنا'})

def post_detail (request, post_id):
    post=  get_object_or_404(Post,pk=post_id)
    comments = post.comments.filter(active=True) #show the comment if it is activated
    #التأكد من صحة البيانات قبل الحفظ
    if request.method == 'POST':
        comment_form = NewComment(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_form = NewComment () #empty the form
    else:
        comment_form = NewComment()

    context={
    'title': post,
    'post': post,
    'comments' : comments,
    'comment_form': comment_form,
    }

    return render(request, 'blog/detail.html', context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/new_post.html'
    form_class = PostCreateForm

    def form_valid(self, form):
        print(self.request.user)
        uploaded_report = self.request.FILES.get('uploaded_report', None)
        if uploaded_report:
            # Check if the file is an Excel file
            if uploaded_report.name.endswith('.xlsx') or uploaded_report.name.endswith('.xls'):
                if uploaded_report.size > 0:
                    fs = FileSystemStorage()
                    filename = fs.save(uploaded_report.name, uploaded_report)

                    # Get the full file path
                    file_path = os.path.join(fs.location, filename)

                    # Initialize the preprocessor with the uploaded file
                    preprocessor = DataPreprocessor(file_path)

                    # Perform preprocessing
                    preprocessed_data = preprocessor.preprocess()

                    # Store file path in session
                    self.request.session['uploaded_file_path'] = file_path
                    
                    # Generate PDF
                    pdf_data = DataPreprocessor.mergepdf(preprocessed_data)  # Assuming a function generate_pdf is defined

                    # Create a variable for the ContentFile
                    pdf_content = pdf_data.getvalue()  # Get the content of the PDF file

                    # Save the generated PDF to the Post model
                    # form.instance.generated_pdf.save('generated_pdf.pdf', ContentFile(pdf_content))

                    # Set the author and process the form
                    form.instance.author = self.request.user
                    form.instance.preprocessed_data = preprocessed_data # Assuming the Post model has a field for this



                    return super().form_valid(form)
                else:
                    # File is empty, display warning message
                    messages.warning(self.request, 'الملف المرفق فارغ!')
                    return super().form_invalid(form)
            else:
                # File is not an Excel file, display warning message
                messages.warning(self.request, 'يرجى إرفاق ملف Excel فقط!')
                return super().form_invalid(form)
        else:
            # File not uploaded, display warning message
            messages.warning(self.request, 'يرجى إرفاق تقرير الالتزام قبل التأكيد!')
            return super().form_invalid(form)
        

def download_combined_pdf(request):
    # Retrieve the file path from the session
    file_path = request.session.get('uploaded_file_path')
    if file_path:
        preprocessor1 = DataPreprocessor(file_path)
        pdf = preprocessor1.mergepdf() 
        
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename=GeneratedReport.pdf'
        response.write(pdf.getvalue()) 
        return response 
    
    else:
        messages.error(request, 'No file path found in session.')
        return redirect('upload') 


class PostUpdateView(UserPassesTestMixin,LoginRequiredMixin,UpdateView):
    model = Post 
    template_name = 'blog/post_update.html'
    form_class = PostUpdateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
       post = self.get_object()
       if self.request.user == post.author:
           return True
       else:
           return False
       
class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    


""" file_path=''
def process_upload(request):
    if request.method == 'POST' and request.FILES['xlsx_file']:
        xlsx_file = request.FILES['xlsx_file']
        fs = FileSystemStorage()
        filename = fs.save(xlsx_file.name, xlsx_file)

        uploaded_file_url = fs.url(filename)
        
        # Load the XLSX file into a DataFrame
        file_path = os.path.join(fs.location, filename)
        #file_path1 = os.path.join(fs.location, filename)

        # Initialize the preprocessor with the uploaded file
        preprocessor = DataPreprocessor(file_path)

        # Perform preprocessing
        list = preprocessor.preprocess()

        return render(request, 'blog/user.html')
    return redirect('upload')
 """

""" @login_required
def download_combined_pdf(request):

    preprocessor1 = DataPreprocessor(file_path)
    pdf=preprocessor1.mergepdf() 
    
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=combined.pdf'
    #response['Content-Length'] = len(pdf_data)
    response.write(pdf.getvalue())
    print("hello")
    return response """

myProject_src/user/views.py
from django.shortcuts import render , redirect
from .forms import UserCreationForm, LoginForm, UserUpdateForm, ProfileUpdateForm
from django .contrib import messages
from django .contrib.auth import authenticate, login, logout
from blog.models import Post
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user= form.save(commit=False)
            new_user.set_password(form.cleaned_data['password1'])
            new_user.save()
            #username = form.cleaned_data['username']
            messages.success(
                request, f'تهانينا {new_user} لقد تمت عملية التسجيل بنجاح.')
            return redirect('login')
    else: 
       form = UserCreationForm()
    return render(request, 'user/register.html', {
        'title': 'التسجيل',
        'form': form,
    })

def login_user(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('profile')
        else:
            messages.warning(
                request, 'هناك خطأ في اسم المستخدم أو كلمة المرور.')

    return render(request, 'user/login.html', {
        'title': 'تسجيل الدخول',
        'form': form,
    })

def logout_user(request):
    logout(request)
    return render(request, 'blog/index.html', {
        'title': 'تسجيل الخروج',
    })

@login_required(login_url='login')
def profile(request):
    posts = Post.objects.filter(author=request.user)
    posts_list = Post.objects.filter(author=request.user)
    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page')
    try:
        posts_list = paginator.page(page)
    except PageNotAnInteger:
        posts_list = paginator.page(1)
    except EmptyPage:
        posts_list = paginator.page(paginator.num_pages)

    return render(request, 'user/profile.html', {
        'title': 'الملف الشخصي',
        'posts': posts,
        'page': page,
        'posts_list' : posts_list
    })

@login_required(login_url='login')
def profile_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            profile_form.save()
            messages.success(
                request, 'تم تحديث الملف الشخصي.')
            return redirect('profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'title': 'تعديل الملف الشخصي',
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'user/profile_update.html', context)

myProject_src/blog/templates/blog/Try.html
#Used Laibraries
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import sacrebleu
import pandas as pd


# Loading the fine-tuned model and its tokenizer 
model_path = r"C:\Users\96659\Downloads\Imtathil_Model\Last_saved_mode"
model = GPT2LMHeadModel.from_pretrained(model_path)
tokenizer = GPT2Tokenizer.from_pretrained(model_path)

# Function to generate text using beam search
def generate_text(prompt, model, tokenizer, max_length, num_return_sequences=1, no_repeat_ngram_size=2, num_beams=10):
    inputs = tokenizer(prompt, return_tensors='pt')
    input_ids = inputs['input_ids']
    
    output_sequences = model.generate(
        input_ids=input_ids,
        max_length=max_length,
        num_return_sequences=num_return_sequences,
        no_repeat_ngram_size=no_repeat_ngram_size,
        num_beams=num_beams,
        early_stopping=True,
        pad_token_id=tokenizer.eos_token_id  
    )

    # Generate the text based on the input
    
    generated_texts = []
    for generated_sequence in output_sequences:
        generated_text = tokenizer.decode(generated_sequence, skip_special_tokens=True)
        generated_texts.append(generated_text)
    
    return generated_texts


prompt = "يجب أن تغطي متطلبات الأمن السيبراني لحماية البريد الإلكتروني للجهة بحد أدنى ما يلي النسخ الاحتياطي و الأرشفة للبريد الإلكتروني"

reference_texts = [["العمل على تحديد متطلبات هذا الضابط و توثيقها في وثيقة متطلبات الأمن السيبراني لحماية البريد الإلكتروني للجهة و اعتمادها من قبل صاحب الصلاحية تحديد التقنيات المتوافقة مع الأنظمة التقنية والبنية التحتية التقنية للجهة لعمل النسخ الاحتياطي و الأرشفة للبريد الإلكتروني للجهة تحديد مدة الاحتفاظ بالنسخ الاحتياطية و الأرشفة للبريد الإلكتروني للجهة العمل على القيام بالنسخ الاحتياطي على مستوى خوادم البريد الإلكتروني للجهة العمل على تفعيل خاصية أرشفة جميع صناديق البريد الإلكتروني للجهة"]]
                    
reference_length = len(tokenizer(reference_texts[0][0], return_tensors='pt')['input_ids'][0])

# Generate the text based on the the reference length
num_return_sequences = 1  #number of sequences to generate
num_beams = 5  #number of beams for beam search
generated_texts = generate_text(prompts[0], model, tokenizer, max_length=reference_length, num_return_sequences=num_return_sequences, no_repeat_ngram_size=2, num_beams=num_beams)

# Initialize lists to store scores
bleu_scores = []
precisions_1gram = []
precisions_2gram = []
precisions_3gram = []
precisions_4gram = []

#Printing The Scores

for i, generated_text in enumerate(generated_texts):
    sacrebleu_score = sacrebleu.corpus_bleu([generated_text], reference_texts)
    bleu_scores.append(sacrebleu_score.score)
    precisions_1gram.append(sacrebleu_score.precisions[0])
    precisions_2gram.append(sacrebleu_score.precisions[1])
    precisions_3gram.append(sacrebleu_score.precisions[2])
    precisions_4gram.append(sacrebleu_score.precisions[3])
    
    print(f"Generated text {i + 1}:")
    print(generated_text)
    print(f"SacreBLEU score: {sacrebleu_score.score:0.2f}")
    print(f"1-gram precision: {sacrebleu_score.precisions[0]:0.2f}")
    print(f"2-gram precision: {sacrebleu_score.precisions[1]:0.2f}")
    print(f"3-gram precision: {sacrebleu_score.precisions[2]:0.2f}")
    print(f"4-gram precision: {sacrebleu_score.precisions[3]:0.2f}")
    print("\n")

print("Reference text length:", reference_length)

myProject_src/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="section wrapper d-flex justify-content-center align-items-center" data-aos="fade-up">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
        <div class="card text-dark card-has-bg click-col">
          <div class="card-img-overlay d-flex flex-column align-items-center"> 
            <div class="card-body text-center">
              <img class="img-fluid rounded-circle border m-2" style="width:120px; height:120px;" src="{{ post.author.profile.image.url }}" alt="صورة الناشر">
              <div class="">
                <span class="text-secondary"> تم إنشـاء التقرير في :{{ post.post_date | date:'d-m-Y' }} </span>
                <h3 style="margin-top: 20%;">{{ post.title }}</h3>
                <p>{{ post.content }}</p>
                <a href="{% url 'download_combined_pdf' %}" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded"> تحميل التقرير </a>
              </div>
            </div>
            <div class="card-footer">
              <div class="form-group btn-editing text-center">
                {% if post.author == user %}
                <a href="{% url 'post-update' post.id %}" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded btn-secondary">تحرير</a>
                <a href="{% url 'post-delete' post.id %}" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded btn-danger">حـذف</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
.wrapper {
  margin: 10vh;
}

.card {
  border: none;
  transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
  overflow: hidden;
  border-radius: 20px;
  min-height: 500px;
  box-shadow: 0 0 12px 0 rgba(0, 0, 0, 0.2);
}

.btn-rounded.btn-md {
  padding: 12px 35px;
  font-size: 16px;
}

.btn-primary,
.btn-primary.disabled {
  background: #02395D;
  border: 1px solid #02395D;
  -webkit-box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
  box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
  -webkit-transition: 0.2s ease-in;
  -o-transition: 0.2s ease-in;
  transition: 0.2s ease-in;
}

.btn-rounded {
  border-radius: 60px;
  padding: 7px 18px;
}

.btn:disabled {
  background-color: #BDBDBD;
  cursor: not-allowed;
}
</style>
{% endblock content %}

myProject_src/blog/templates/blog/latest_posts.html
<ul class="list-group-flush latest-post">
    {% for post in l_posts %}
    <li class="list-group-item latest-post-item">
        <a class="text-dark" href="{% url 'detail' post.id %}" style="text-decoration: none;">{{post.title}}</a>
    </li>
    {% empty %}
    <li class="list-group-item latest-post-item">لا يوجد تقارير</li>
    {% endfor %}
</ul>

myProject_src/blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<section class="wrapper d-flex justify-content-center align-items-center"  data-aos="fade-up">
    <div class="container justify-content-center">
      <div class="row justify-content-center">
        <div class="col-sm-12 col-md-6 col-lg-4 mb-4 justify-content-center">
          {% if messages %}
          <div class="alert alert-warning" role="alert">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
          </div>
          {% endif %}
          <div class="card text-dark card-has-bg click-col justify-content-center" >
            <img class="card-img d-none" src="#" alt="#">
              <div class="card-img-overlay d-flex flex-column justify-content-center">
               <div class="card-body">
                <legend class="border-bottom pb-1 mb-3">إنشـاء تقريـر التزام جديـد</legend>

                    <form method="POST" enctype="multipart/form-data" id="uploadForm" >
                        {% csrf_token %}
                        {{form|crispy}}      
                </div>
                <input type="file" name="uploaded_report" id="id_uploaded_report" style="display: none" >
                
                        <div class="card-footer">
                        <div class="media text-center">
                            <!-- a button to confirm the changes -->
                            <input class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded" type="submit" value="تأكيد">  
                        </div>
                        </div>
              </div>
            </div>
                    </form>

          </div>

          <div class="col-md-4" style="margin-right: 10%;">
            <h3 style="color:#CBE54E ; margin-top: 40%; ">  NCA's ECC</h3>
            <h1 style="color:#3B5286;"> قياس الالتزام</h1>
            <h3 style="color:#3B5286 ;">  الضوابط الأساسية للأمن السيبراني </h3>
            
          </div>
      </div>
    </div>
  </section>

<style>

    .wrapper {
      margin: 10vh;
      display: flex;
      justify-content: center;
      align-items: center;

    }
  
    .card {
      border: none;
      transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
      overflow: hidden;
      border-radius: 20px;
      min-height: 570px;
      box-shadow: 0 0 12px 0 rgba(0, 0, 0, 0.2);
    }
  

    .btn-rounded.btn-md {
        padding: 12px 35px;
        font-size: 16px;
    }
  
    .btn-primary,
    .btn-primary.disabled {
        background: #3B5286;
        border: 1px solid #3B5286;
        -webkit-box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
        box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
        -webkit-transition: 0.2s ease-in;
        -o-transition: 0.2s ease-in;
        transition: 0.2s ease-in;
    }
  
    .btn-rounded {
        border-radius: 60px;
        padding: 7px 18px;
    }
  
    .btn:disabled {
      background-color: #BDBDBD;
      cursor: not-allowed;
    }

  </style>
  
{% endblock content %}

myProject_src/blog/templates/blog/user.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        h1 {
            text-align: center;
            margin-top: 50px;
            color: #333;
        }
        .btn {
            display: block;
            width: 200px;
            margin: 20px auto;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .btn:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Download Combined PDF</h1>
    <a href="{% url 'download_combined_pdf' %}" class="btn">Download PDF</a>
</body>
</html>
 -->